version: '3.8'

services:
  advisory-august:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=advisory_august_production_secret_key_2024
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./public:/app/public
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/auth/verify"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 개발 환경용 서비스
  advisory-august-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=advisory_august_dev_secret_key_2024
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    profiles:
      - dev
