services:
  - type: web
    name: advisory-august
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ADVISOR_API_URL
        value: https://www.advisorapi.io
      - key: ADVISOR_API_KEY
        sync: false  # 실제 API 키는 Render 대시보드에서 설정
